FROM maven:3.8.8-eclipse-temurin-17-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY src /app/src

RUN mvn clean package -DskipTests




FROM openjdk:17-jdk-slim

WORKDIR /app
COPY --from=build /app/target/app-1.0.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]